Update codeql.yml

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -8,47 +8,56 @@ on:
 jobs:
   analyze:
     runs-on: ubuntu-latest
+    permissions:
+      actions: read
+      contents: read
+      security-events: write
+    strategy:
+        fail-fast: false
+        matrix:
+          language: [ 'java-kotlin' ]
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Setup CodeQL
-        uses: github/codeql-action/setup@v2
+      - name: Checkout repository
+        uses: actions/checkout@v3
+   
+      # Initializes the CodeQL tools for scanning.
+      - name: Initialize CodeQL
+        uses: github/codeql-action/init@v2
         with:
-          languages: java
-
+          languages: ${{ matrix.language }}
+  
       - name: Build CodeQL database
         run: codeql database create --language=java --source-root=src --output=db
-
+  
       - name: Run CodeQL analysis
         run: codeql database analyze --language=java --database=db --output=results
-
+  
       - name: Upload CodeQL results
         uses: actions/upload-artifact@v2
         with:
           name: codeql-results
           path: results
-
+  
       - name: Display CodeQL results
         run: cat results/*.sarif
       - name: List SARIF Issues and Fail Workflow on Critical Issues
         run: |
-          sarif_file="/home/runner/work/aidevsecopsdemo/results/*.sarif"
-      
-          if [ -f "$sarif_file" ]; then
-            critical_issues=$(grep -c '"level": "error"' "$sarif_file")
-            if [ "$critical_issues" -gt 0 ]; then
-              echo "Critical issues found in SARIF results:"
-              grep -B 1 '"level": "error"' "$sarif_file"
-              echo "Failing the workflow due to critical issues."
-              exit 1  # Fail the workflow
+            sarif_file="/home/runner/work/aidevsecopsdemo/results/*.sarif"
+        
+            if [ -f "$sarif_file" ]; then
+              critical_issues=$(grep -c '"level": "error"' "$sarif_file")
+              if [ "$critical_issues" -gt 0 ]; then
+                echo "Critical issues found in SARIF results:"
+                grep -B 1 '"level": "error"' "$sarif_file"
+                echo "Failing the workflow due to critical issues."
+                exit 1  # Fail the workflow
+              else
+                echo "No critical issues found in SARIF results."
+              fi
             else
-              echo "No critical issues found in SARIF results."
+              echo "SARIF results file not found at $sarif_file."
             fi
-          else
-            echo "SARIF results file not found at $sarif_file."
-          fi
-          shell: /usr/bin/bash -e {0}
+            shell: /usr/bin/bash -e {0}
 
 
